In [1]:
import numpy as np

# =========================
# 1. Create the array
# =========================
A = np.arange(1, 21).reshape(4, 5)

print("A:\n", A)
print("dtype:", A.dtype)
print("ndim:", A.ndim)
print("shape:", A.shape)
print("size:", A.size)
print("itemsize:", A.itemsize)

# Create B by reshaping A
B = A.reshape(5, 4)
print("\nB (reshaped A):\n", B)


# =========================
# 2. Given two arrays
# =========================
a = np.array([[10, 0, 0, 1],
              [10, 10, 10, 1],
              [20, 20, 20, 1],
              [30, 30, 30, 1]])

b = np.array([0, 1, 2, 1])

# c = a + b
c = a + b
print("\nc = a + b:\n", c)

# Boolean mask (c >= 22)
mask = (c >= 22)
print("\nMask (c >= 22):\n", mask)

# Count values where c >= 22
count = np.sum(c >= 22)
print("\nCount of values >= 22:", count)


# =========================
# 3. Grades statistics
# =========================
grades = np.array([[87, 96, 70],
                   [100, 87, 90],
                   [94, 77, 90],
                   [100, 81, 82]])

print("\nOverall:")
print("Sum:", np.sum(grades))
print("Min:", np.min(grades))
print("Max:", np.max(grades))
print("Mean:", np.mean(grades))
print("Std:", np.std(grades))
print("Var:", np.var(grades))

print("\nMean per column:", np.mean(grades, axis=0))
print("Mean per row:", np.mean(grades, axis=1))
print("Max per row:", np.max(grades, axis=1))


# =========================
# 4. 2x3 array operations
# =========================
arr = np.array([[2, 4, 6],
                [1, 3, 5],
                [7, 9, 11]])

print("\nSum of each row:", np.sum(arr, axis=1))
print("Sum of each column:", np.sum(arr, axis=0))
print("Overall mean:", np.mean(arr))


# =========================
# 5. Array operations
# =========================
A = np.array([[10, 20, 30],
              [40, 50, 60]])

B = np.array([1, 2, 3])

print("\nAdd B to A:\n", A + B)
print("\nMultiply A by 2:\n", A * 2)
print("\nSubtract 5 from A:\n", A - 5)


# =========================
# 6. Index operations
# =========================
grades = np.array([[70, 85, 90],
                   [88, 76, 95],
                   [60, 80, 72]])

# Index of largest value in whole array
max_index = np.unravel_index(np.argmax(grades), grades.shape)
print("\nIndex of largest value:", max_index)

# Index of highest grade in each row
row_max_indices = np.argmax(grades, axis=1)
print("Index of highest grade per row:", row_max_indices)

# Index of lowest grade in each column
col_min_indices = np.argmin(grades, axis=0)
print("Index of lowest grade per column:", col_min_indices)


# =========================
# 7. Distance functions
# =========================
def manhattan_distance(x1, y1, x2, y2):
    return abs(x2 - x1) + abs(y2 - y1)

def euclidean_distance(x1, y1, x2, y2):
    return np.sqrt((x2 - x1)*2 + (y2 - y1)*2)

# Example
print("\nManhattan Distance:", manhattan_distance(1, 2, 4, 6))
print("Euclidean Distance:", euclidean_distance(1, 2, 4, 6))

A:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
dtype: int64
ndim: 2
shape: (4, 5)
size: 20
itemsize: 8

B (reshaped A):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]

c = a + b:
 [[10  1  2  2]
 [10 11 12  2]
 [20 21 22  2]
 [30 31 32  2]]

Mask (c >= 22):
 [[False False False False]
 [False False False False]
 [False False  True False]
 [ True  True  True False]]

Count of values >= 22: 4

Overall:
Sum: 1054
Min: 70
Max: 100
Mean: 87.83333333333333
Std: 8.792357792739987
Var: 77.30555555555556

Mean per column: [95.25 85.25 83.  ]
Mean per row: [84.33333333 92.33333333 87.         87.66666667]
Max per row: [ 96 100  94 100]

Sum of each row: [12  9 27]
Sum of each column: [10 16 22]
Overall mean: 5.333333333333333

Add B to A:
 [[11 22 33]
 [41 52 63]]

Multiply A by 2:
 [[ 20  40  60]
 [ 80 100 120]]

Subtract 5 from A:
 [[ 5 15 25]
 [35 45 55]]

Index of largest value: (np.int64(1), np.int64(2))
Index of highest grade per 

In [2]:
import numpy as np

# =========================
# 1) np.where + split + reshape
# =========================
x = np.array([1, 2, 3, 4, 5, 6, 7])

# indices where values > 3
indices = np.where(x > 3)
print("Indices where x > 3:", indices)

# split into 3 parts
part1, part2, part3 = np.split(x, [2, 5])
print("Split parts:", part1, part2, part3)

# expand dims then squeeze
x_expanded = np.expand_dims(x, axis=0)
print("Expanded shape:", x_expanded.shape)

x_squeezed = np.squeeze(x_expanded)
print("Squeezed shape:", x_squeezed.shape)


# =========================
# 2) Matrix operations
# =========================
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

v = np.array([2, 4])

# element-wise
print("A * B:\n", A * B)

# matrix multiplication
print("A @ B:\n", A @ B)

# broadcasting
print("A * v:\n", A * v)


# =========================
# 3) Random + unique + counts + unique rows
# =========================
np.random.seed(0)

matrix = np.random.randint(-5, 6, (4, 4))
print("Random matrix:\n", matrix)

# unique values and counts
values, counts = np.unique(matrix, return_counts=True)
print("Unique values:", values)
print("Counts:", counts)

# unique rows
unique_rows = np.unique(matrix, axis=0)
print("Unique rows:\n", unique_rows)


# =========================
# 4) Given array unique rows + counts
# =========================
a = np.array([[1, 0, 0],
              [1, 0, 0],
              [2, 3, 4]])

unique_rows_a, counts_a = np.unique(a, axis=0, return_counts=True)
print("Unique rows in a:\n", unique_rows_a)
print("Counts:", counts_a)


# =========================
# 5) argsort + unravel_index
# =========================
x = np.array([2, 0, 1, 5, 4, 1, 9])

indices_sorted = np.argsort(x)
print("Sorted indices:", indices_sorted)
print("Sorted x:", x[indices_sorted])

A = np.array([[3, 8, 1],
              [6, 2, 9]])

min_index = np.unravel_index(np.argmin(A), A.shape)
print("Min value location (row, col):", min_index)


# =========================
# 6) Numpy Lab - Part 2
# =========================

# Matrix from table
table = np.array([
    [5, 8, 2, 7],
    [1, 9, 4, 3],
    [6, 0, 11, 10],
    [12, 13, 14, 15]
])

# second row
print("Second row:", table[1])

# third column
print("Third column:", table[:, 2])

# sub-table R2-R3 & C2-C3
print("Sub-table:\n", table[1:3, 1:3])


# =========================
# 7) Students scores
# =========================
scores = np.array([
    [70, 80, 90],
    [60, 75, 85],
    [88, 92, 79],
    [55, 65, 72]
])

# increase Physics (+5) column index = 1
scores[:, 1] += 5

# replace first student
scores[0] = [100, 100, 100]

# set last column (CS) to zero
scores[:, 2] = 0

print("Updated scores:\n", scores)

Indices where x > 3: (array([3, 4, 5, 6]),)
Split parts: [1 2] [3 4 5] [6 7]
Expanded shape: (1, 7)
Squeezed shape: (7,)
A * B:
 [[ 5 12]
 [21 32]]
A @ B:
 [[19 22]
 [43 50]]
A * v:
 [[ 2  8]
 [ 6 16]]
Random matrix:
 [[ 0 -5 -2 -2]
 [ 2  4 -2  0]
 [-3 -1  2  1]
 [ 3  3  5 -4]]
Unique values: [-5 -4 -3 -2 -1  0  1  2  3  4  5]
Counts: [1 1 1 3 1 2 1 2 2 1 1]
Unique rows:
 [[-3 -1  2  1]
 [ 0 -5 -2 -2]
 [ 2  4 -2  0]
 [ 3  3  5 -4]]
Unique rows in a:
 [[1 0 0]
 [2 3 4]]
Counts: [2 1]
Sorted indices: [1 2 5 0 4 3 6]
Sorted x: [0 1 1 2 4 5 9]
Min value location (row, col): (np.int64(0), np.int64(2))
Second row: [1 9 4 3]
Third column: [ 2  4 11 14]
Sub-table:
 [[ 9  4]
 [ 0 11]]
Updated scores:
 [[100 100   0]
 [ 60  80   0]
 [ 88  97   0]
 [ 55  70   0]]
